services:
  djs-bot:
    container_name: djs-bot
    build:
      context: ..
      dockerfile: ./docker/djs-bot/Dockerfile
    restart: "unless-stopped"
    init: true
    environment:
      - TOKEN=${TOKEN}
      - CLIENTID=${CLIENTID}
      - CLIENTSECRET=${CLIENTSECRET}
      - DEVUID=${DEVUID}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
    stdin_open: true
    tty: true
    volumes:
      - ../djs-bot:/djs-bot
    ports:
      - "8080:8080"
      - "3001:3001"
    working_dir: /djs-bot
    command: ["npm", "run", "${ENABLE:-start}"]
    depends_on:
      - postgres-db
      - lavalink

  # dashboard:
  #   container_name: dashboard
  #   image: node:latest
  #   restart: "unless-stopped"
  #   init: true
  #   stdin_open: true
  #   tty: true
  #   volumes:
  #     - ../dashboard:/dashboard
  #   ports:
  #     - "3000:3000"
  #   working_dir: /dashboard
  #   command: ["npm", "run", "build-and-start"]

  postgres-db:
    image: postgres:15.2-alpine
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD:  root
      POSTGRES_USER:      root
      POSTGRES_DB:        base
      PGPORT:             5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  lavalink:
    image: fredboat/lavalink:3
    restart: unless-stopped
    hostname: docker.lavalink
    environment:
      - PLUGINS_YOUTUBE_OAUTH_REFRESHTOKEN=${PLUGINS_YOUTUBE_OAUTH_REFRESHTOKEN}
    volumes:
      - ./lavalink/application.yml:/opt/Lavalink/application.yml
      # - ./lavalink/plugins/:/opt/Lavalink/plugins
    depends_on:
      - yt-cipher

  yt-cipher:
    image: ghcr.io/kikkia/yt-cipher:master
    hostname: docker.yt-cipher
    restart: unless-stopped
    environment:
      API_TOKEN: test

volumes:
  postgres_data:
